### PR TITLE
#299 fix subject autofill

### LINKED ISSUE #299: Subject not always auto-filled
I've noticed a bunch of times when creating a new resource, that the `subject` field was empty. This should contain a generated string. 

- Open your drive
- Create new resource
- Select some class from the dropdown (one without an auto-submit handler, so don't pick folder or document)
- Subject is empty

Thanks to @adileo

### PR DESCRIPTION
**Pull request by Polleps**
PR Checklist:

- [x] Link to related issues: closes #299 
- [ ] Add changelog entry linking to issue
- [x] Add tests (if needed)
- [ ] If dependent on server-side changes: link to PR on `atomic-data-rust`
- [ ] If new feature: added in description / readme

### CODE REVIEW

File: data-browser/src/components/forms/NewForm/useNewForm.ts [hunk 1]
```diff
@@ -58,7 +62,7 @@ export const useNewForm = (
     store
       .renameSubject(oldSubject, defferedSubjectValue)
       .then(() => {
-        setSubject(defferedSubjectValue);
+        // setSubject(defferedSubjectValue);
```
Comment (joepio) [inline data-browser/src/components/forms/NewForm/useNewForm.ts:65]: ?

File: data-browser/tests/e2e.spec.ts [hunk 2]
```diff
@@ -422,12 +422,11 @@ test.describe('data-browser', async () => {
     await signIn(page);
     await page.locator(`${currentDriveTitle} > text=localhost`);
 
-    const dropdownId = await page
-      .locator(sideBarDriveSwitcher)
-      .getAttribute('aria-controls');
-
     await page.click(sideBarDriveSwitcher);
     // temp disable for trailing slash
+    // const dropdownId = await page
```
Comment (joepio) [inline data-browser/tests/e2e.spec.ts:427]: ?

**Review by joepio — APPROVED** [review]

**Comment by joepio** [comment]
E2E succeeding locally
